[package]
name = "kampung_aktif_harian"
version = "0.0.1"

[addresses]
kampung_account = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "main", subdir = "aptos-move/framework/aptos-framework" }
