[package]
name = "KampungWeb3"
version = "1.0.0"
authors = []

[addresses]
kampung = "0x23adb5190b461f2821b3cafef93249837961a2c461fd103e94dd365f11bdb0b1"

[dev-addresses]
kampung = "0x23adb5190b461f2821b3cafef93249837961a2c461fd103e94dd365f11bdb0b1"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"
